# Generated by Django 4.2.2 on 2023-07-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testi_icon', models.CharField(max_length=50)),
                ('testi_name', models.CharField(max_length=50)),
                ('testi_sub_name', models.CharField(max_length=80)),
                ('testi_desc', models.CharField(max_length=80)),
                ('testi_follow', models.TextField()),
            ],
        ),
    ]
