# Generated by Django 4.2.2 on 2023-07-14 05:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='apply_desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
