# Generated by Django 4.2.2 on 2023-07-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_info', models.CharField(max_length=50)),
                ('create_desc', models.CharField(max_length=80)),
                ('create_link', models.TextField()),
            ],
        ),
    ]
